### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by jonson-baby** [Kr4ken-9/DAB#36]
I GET THIS ERROR

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import discord
  File "D:\PYTHON\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "D:\PYTHON\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "D:\PYTHON\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "D:\PYTHON\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax

**Comment by EliteDaMyth** [comment]
Use python 3.x

**Comment by Kr4ken-9** [comment]
I'm assuming this is solved
