### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by CrowNasty** [Kr4ken-9/DAB#43]
C:\Users\Tim\Documents\GitHub\DAB\src\config.py:30: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(file)
Traceback (most recent call last):
  File "C:\Users\Tim\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\bot.py", line 575, in _load_from_module_spec
    setup(self)
  File "C:\Users\Tim\Documents\GitHub\DAB\src\COMMANDS.py", line 35, in setup
    client.add_cog(Commands(client))
  File "C:\Users\Tim\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\bot.py", line 475, in add_cog
    raise TypeError('cogs must derive from Cog')
TypeError: cogs must derive from Cog

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 46, in <module>
    client.load_extension("src.COMMANDS")
  File "C:\Users\Tim\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\bot.py", line 620, in load_extension
    self._load_from_module_spec(lib, name)
  File "C:\Users\Tim\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\bot.py", line 579, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'src.COMMANDS' raised an error: TypeError: cogs must derive from Cog

**Comment by RohanJnr** [comment]
in cogs, the class should inherit from `discord.ext.commands.Cog`

**Comment by CrowNasty** [comment]
Okay so I have to add that where?

**Comment by Kr4ken-9** [comment]
In order to fix this you will have to look at [line 6 from src.Commands:](https://github.com/Kr4ken-9/DAB/blob/master/src/COMMANDS.py#L6)

```py
import asyncio
from discord.ext import commands
from src import utils


class Commands:
    def __init__(self, client):
        self.client = client
        self.shared_config = client.shared
        self.pokecord = client.pokecord
```

Line 6 being: `class Commands:`

As @RohanJnr said, the class Commands must inherit discord.ext.commands.Cog. Since that class is imported on line 2, it can be shortened to commands.Cog. So, to answer your question, you must change line 6 to make Commands inherit commands.Cog

If you have trouble understanding inheritance, there are multiple articles explaining it. [This is an example of one.](https://www.python-course.eu/python3_inheritance.php) To just fix it though, simply change `class Commands:` to `class Commands(commands.Cog):`

If you would like to, you can even submit this change as a pull request and I will accept it. I encountered this problem when I was still working on this project and it is part of many small changes that I never pushed, so that is why it persists in this repository.

**Comment by CrowNasty** [comment]
Its not allowing my to summit a pull request also now I am getting  this:
>
    class Commands(commands.cog):
TypeError: module() takes at most 2 arguments (3 given)

**Comment by Kr4ken-9** [comment]
This error stems from src/config.py. Specifically, the very last line, [line 30:](https://github.com/Kr4ken-9/DAB/blob/master/src/config.py#L30)

```py
    def load_config(self):
        """Loads path as a yaml config"""
        with open(self.path, "r") as file:
            return yaml.load(file)
```

In order to fix this error, you will need to specify a loader for pyyaml. I chose to use the SafeLoader when I was still working on this project. But I no longer remember what the difference is, so if you're interested in that I would follow the link listed in the exception for further details.

To tell pyyaml to load files using the SafeLoader, replace `return yaml.load(file)` with `return yaml.load(file, Loader=yaml.SafeLoader)`

**Comment by CrowNasty** [comment]
I did that now I got this error

$ python main.py
Traceback (most recent call last):
  File "C:\Users\timmy\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\ext\commands\bot.py", line 616, in load_extension
    lib = importlib.import_module(name)
  File "C:\Users\timmy\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src.COMMANDS.py'; 'src.COMMANDS' is not a package

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 46, in <module>
    client.load_extension("src.COMMANDS.py")
  File "C:\Users\timmy\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\ext\commands\bot.py", line 618, in load_extension
    raise errors.ExtensionNotFound(name, e) from e
discord.ext.commands.errors.ExtensionNotFound: Extension 'src.COMMANDS.py' could not be loaded.

**Comment by Kr4ken-9** [comment]
Although I never figured out what the final error was, as of the latest commit the first two errors are fixed and DAB is running perfectly on my machine. I am going to close this since I believe (and hope) the errors are solved.
