### ISSUE TITLE
Setup Complete But Won't Open

### ISSUE THREAD

**Issue by wulavi** [Kr4ken-9/DAB#64]
Hi! I recently downloaded the newest version of DAB master for pokecord. I completed all of the requirements and finished the setup but when I try to open the "main.py" program, it crashes/doesn't work. Here is an example of what I mean; [Video](https://gyazo.com/7c07e577d812b0013136094624d884c2). If you could help me out, that would be great. Thank you!

**Comment by wulavi** [comment]
also, here are screenshots of what it said; ![image](https://user-images.githubusercontent.com/68147160/87222003-7693d080-c39a-11ea-9f6f-ff663f261de8.png)![image](https://user-images.githubusercontent.com/68147160/87222012-84495600-c39a-11ea-81ac-a43d2581a59f.png)

**Comment by Kr4ken-9** [comment]
When did you complete the setup? It appears to be trying to connect to `discordapp.com` but it really shouldn't be. Maybe try running `git pull` and `python -m pip install -r requirements.txt` again to update the discord.py library.

**Comment by wulavi** [comment]
I completed the setup yesterday. Where should i write the commands? I manually downloaded the requirements one by one instead of using the file. My apologies for bothering you, I dont really understand how python, git, etc works.

**Comment by wulavi** [comment]
Alright, so I used git pull and python -m pip install -r requirements.txt but the same problem occurred.

**Comment by Kr4ken-9** [comment]
In that case I'm not sure. There really shouldn't be any outgoing connections to `discordapp.com`. I had similar SSL errors in the past but they solved themselves, so I don't have much advice for you.

**Comment by wulavi** [comment]
Aw okay, thank you for trying though

**Comment by wulavi** [comment]
I've installed a new certificate and the SSL certificate_verify_fail issue is gone. However, there is a new issue;
Traceback (most recent call last):
  File "main.py", line 105, in <module>
    client.run(shared_yaml["token"], bot=False)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 632, in run
    return future.result()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 613, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 576, in start
    await self.login(*args, bot=bot)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 434, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 260, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 224, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 0): <html><title>Error 400 (Bad Request)!!1</title></html>
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001B9A9239160>
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

Anything you could do to fix this?

**Comment by wulavi** [comment]
Oh! I got it to work! Thank you for all of your help.
